name: EpicSpawners
description: EpicSpawners
version: maven-version-number
softdepend: [ Holograms, HolographicDisplays, CMI, Vault, PlayerPoints, UltimateStacker, StackMob, SkyBlock, Towny, RedProtect, Kingdoms, PlotSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, PlaceholderAPI, ShopGUIPlus, UltimateClaims, Lands, BentoBox, EpicAnchors ]
main: com.craftaro.epicspawners.EpicSpawners
author: Craftaro
api-version: 1.13
commands:
  es:
    description: I have no idea.
    default: true
    aliases: [ EpicSpawners ]
    usage: /<command> [reload]
  SpawnerStats:
    description: I have no idea.
    default: false
    usage: /<command> [reload]
  SpawnerShop:
    description: I have no idea.
    default: false
    usage: /<command> [reload]
